# Generated by Django 6.1.1 on 2026-09-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_couponmodel_commentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponmodel",
            name="status",
            field=models.IntegerField(
                choices=[(1, "نمایش"), (2, "عدم نمایش")], default=2
            ),
        ),
    ]
