# Generated by Django 6.1.1 on 2026-09-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_couponmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment",
                to="products.productmodel",
            ),
        ),
    ]
